# Generated by Django 5.0 on 2023-12-13 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="facility",
            new_name="facilities",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="house_rule",
            new_name="house_rules",
        ),
    ]
