# Generated by Django 5.0 on 2023-12-20 05:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_initial"),
        ("rooms", "0005_alter_roomtype_options_alter_room_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reservaction",
            new_name="Reservation",
        ),
    ]
