# Generated by Django 5.0 on 2023-12-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ("-created",)},
        ),
    ]
